services:
  front:
    image: giftwhisper/giftwhisper-front-staging
    ports:
      - 5173:5173

  back:
    image: giftwhisper/giftwhisper-server-staging
    ports:
      - 5500:5500
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./logs:/var/log/nginx
    ports:
      - ${GATEWAY_PORT:-8000}:80
    depends_on:
      - back
      - front

  db:
    image: postgres:17-alpine
    ports:
      - 3001:5432
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  dbdata:
    driver: local
  db_test_data:
    driver: local
  pgadmin_data:
    driver: local
