export const mockUserData = [
  {
    first_name: "John",
    last_name: "Doe",
    date_of_birth: new Date("1990-05-15"),
    email: `john.doe-${Date.now()}@example.com`,
    password: "John@12345",
    is_verified: true,
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    date_of_birth: new Date("1985-08-20"),
    email: `jane.smith-${Date.now()}@example.com`,
    password: "Jane@54321",
    is_verified: true,
  },
  {
    first_name: "Michael",
    last_name: "Johnson",
    date_of_birth: new Date("1992-03-10"),
    email: `michael.johnson-${Date.now()}@example.com`,
    password: "Miche@l123",
    is_verified: true,
  },
  {
    first_name: "Emily",
    last_name: "Davis",
    date_of_birth: new Date("1991-12-01"),
    email: `emily.davis-${Date.now()}@example.com`,
    password: "Em1ly@D@vi5",
    is_verified: true,
  },
  {
    first_name: "Chris",
    last_name: "Martinez",
    date_of_birth: new Date("1988-02-25"),
    email: `chris.martinez-${Date.now()}@example.com`,
    password: "Chr1s@M@rt",
    is_verified: true,
  },
  {
    first_name: "Sarah",
    last_name: "Brown",
    date_of_birth: new Date("1994-09-11"),
    email: `sarah.brown-${Date.now()}@example.com`,
    password: "Sarah@1234",
    is_verified: true,
  },
  {
    first_name: "David",
    last_name: "Wilson",
    date_of_birth: new Date("1993-11-29"),
    email: `david.wilson-${Date.now()}@example.com`,
    password: "Dav!d@2023",
    is_verified: true,
  },
  {
    first_name: "Laura",
    last_name: "Miller",
    date_of_birth: new Date("1995-07-15"),
    email: `laura.miller-${Date.now()}@example.com`,
    password: "L@uraM1ll3r",
    is_verified: true,
  },
  {
    first_name: "Daniel",
    last_name: "Moore",
    date_of_birth: new Date("1996-06-19"),
    email: `daniel.moore-${Date.now()}@example.com`,
    password: "D@ni3lMoo0re",
    is_verified: true,
  },
  {
    first_name: "Olivia",
    last_name: "Taylor",
    date_of_birth: new Date("1992-05-04"),
    email: `olivia.taylor-${Date.now()}@example.com`,
    password: "Ol!v1@T@yl0r",
    is_verified: true,
  },
  {
    first_name: "William",
    last_name: "Anderson",
    date_of_birth: new Date("1987-10-02"),
    email: `william.anderson-${Date.now()}@example.com`,
    password: "Will1@m@nd3r",
    is_verified: true,
  },
  {
    first_name: "Sophia",
    last_name: "Thomas",
    date_of_birth: new Date("1993-12-10"),
    email: `sophia.thomas-${Date.now()}@example.com`,
    password: "S0ph!@T#omas",
    is_verified: true,
  },
  {
    first_name: "James",
    last_name: "Jackson",
    date_of_birth: new Date("1991-01-28"),
    email: `james.jackson-${Date.now()}@example.com`,
    password: "Jam3s!Jack",
    is_verified: true,
  },
  {
    first_name: "Ava",
    last_name: "White",
    date_of_birth: new Date("1994-04-16"),
    email: `ava.white-${Date.now()}@example.com`,
    password: "Av@Wh!t3y",
    is_verified: true,
  },
  {
    first_name: "Ethan",
    last_name: "Harris",
    date_of_birth: new Date("1996-02-03"),
    email: `ethan.harris-${Date.now()}@example.com`,
    password: "Eth@n@1234",
    is_verified: true,
  },
  {
    first_name: "Charlotte",
    last_name: "Martin",
    date_of_birth: new Date("1990-09-19"),
    email: `charlotte.martin-${Date.now()}@example.com`,
    password: "Ch@rL0tt3@21",
    is_verified: true,
  },
  {
    first_name: "Benjamin",
    last_name: "Garcia",
    date_of_birth: new Date("1988-11-04"),
    email: `benjamin.garcia-${Date.now()}@example.com`,
    password: "B3nJ@M!n_G@r",
    is_verified: true,
  },
  {
    first_name: "Mia",
    last_name: "Rodriguez",
    date_of_birth: new Date("1995-12-25"),
    email: `mia.rodriguez-${Date.now()}@example.com`,
    password: "M!@R0dr!gu3z",
    is_verified: true,
  },
  {
    first_name: "Alexander",
    last_name: "Lee",
    date_of_birth: new Date("1990-07-21"),
    email: `alexander.lee-${Date.now()}@example.com`,
    password: "A!3xL3@nd3r",
    is_verified: true,
  },
  {
    first_name: "Zoe",
    last_name: "Perez",
    date_of_birth: new Date("1993-10-09"),
    email: `zoe.perez-${Date.now()}@example.com`,
    password: "Z0eP@r3zZ!2",
    is_verified: true,
  },
  {
    first_name: "Lucas",
    last_name: "Clark",
    date_of_birth: new Date("1992-04-23"),
    email: `lucas.clark-${Date.now()}@example.com`,
    password: "Luc@5Cl@rk",
    is_verified: true,
  },
  {
    first_name: "Amelia",
    last_name: "Rodgers",
    date_of_birth: new Date("1991-06-13"),
    email: `amelia.rodgers-${Date.now()}@example.com`,
    password: "Am3l!@R0dg3rs",
    is_verified: true,
  },
  {
    first_name: "Elijah",
    last_name: "Young",
    date_of_birth: new Date("1994-05-17"),
    email: `elijah.young-${Date.now()}@example.com`,
    password: "EliJ@hY0ung",
    is_verified: true,
  },
  {
    first_name: "Isabella",
    last_name: "King",
    date_of_birth: new Date("1996-03-12"),
    email: `isabella.king-${Date.now()}@example.com`,
    password: "Is@B3ll@K1ng",
    is_verified: true,
  },
  {
    first_name: "Henry",
    last_name: "Scott",
    date_of_birth: new Date("1990-01-29"),
    email: `henry.scott-${Date.now()}@example.com`,
    password: "H3nry@Sc0tt",
    is_verified: true,
  },
  {
    first_name: "Scarlett",
    last_name: "Lopez",
    date_of_birth: new Date("1989-04-07"),
    email: `scarlett.lopez-${Date.now()}@example.com`,
    password: "Sc@rL3tLopez",
    is_verified: true,
  },
  {
    first_name: "Jack",
    last_name: "Gonzalez",
    date_of_birth: new Date("1992-07-30"),
    email: `jack.gonzalez-${Date.now()}@example.com`,
    password: "J@ck123Gonz",
    is_verified: true,
  },
  {
    first_name: "Amos",
    last_name: "Nelson",
    date_of_birth: new Date("1991-10-21"),
    email: `amos.nelson-${Date.now()}@example.com`,
    password: "A!m0s@Nel$on",
    is_verified: true,
  },
  {
    first_name: "Hannah",
    last_name: "Carter",
    date_of_birth: new Date("1989-05-14"),
    email: `hannah.carter-${Date.now()}@example.com`,
    password: "H@nnah123C@rt",
    is_verified: true,
  },
  {
    first_name: "Gabriel",
    last_name: "Mitchell",
    date_of_birth: new Date("1992-01-10"),
    email: `gabriel.mitchell-${Date.now()}@example.com`,
    password: "G@br13lM!tch",
    is_verified: true,
  },
  {
    first_name: "Lily",
    last_name: "Perez",
    date_of_birth: new Date("1994-11-28"),
    email: `lily.perez-${Date.now()}@example.com`,
    password: "L!lyP@r3zL!",
    is_verified: true,
  },
  {
    first_name: "Matthew",
    last_name: "Roberts",
    date_of_birth: new Date("1986-12-16"),
    email: `matthew.roberts-${Date.now()}@example.com`,
    password: "M@tthewR@123",
    is_verified: true,
  },
  {
    first_name: "Grace",
    last_name: "Wright",
    date_of_birth: new Date("1993-05-21"),
    email: `grace.wright-${Date.now()}@example.com`,
    password: "Gr@ceWri9ht",
    is_verified: true,
  },
  {
    first_name: "Samuel",
    last_name: "Evans",
    date_of_birth: new Date("1987-09-03"),
    email: `samuel.evans-${Date.now()}@example.com`,
    password: "SamU3l@Ev@ns",
    is_verified: true,
  },
  {
    first_name: "Harper",
    last_name: "Hall",
    date_of_birth: new Date("1995-08-06"),
    email: `harper.hall-${Date.now()}@example.com`,
    password: "H@rp3rH@ll!",
    is_verified: true,
  },
  {
    first_name: "Oliver",
    last_name: "Allen",
    date_of_birth: new Date("1991-03-15"),
    email: `oliver.allen-${Date.now()}@example.com`,
    password: "0l!v3r@1234",
    is_verified: true,
  },
  {
    first_name: "Sofia",
    last_name: "Young",
    date_of_birth: new Date("1996-10-19"),
    email: `sofia.young-${Date.now()}@example.com`,
    password: "S0f!@Y0ng5",
    is_verified: true,
  },
];
