name: main-client

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Ne se déclenche que sur push (après merge), pas sur PR
    if: github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      # --- FRONTEND ---
      - name: Install frontend deps
        run: npm ci
        working-directory: ./frontend

      # - name: Run frontend tests
      #   run: npm test
      #   working-directory: ./frontend

      # --- GIT SHA ---
      - name: Get short SHA
        id: sha
        run: echo "value=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # --- DOCKER ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push for frontend
        id: frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPO }}-client:latest
            ${{ vars.DOCKERHUB_REPO }}-client:${{ steps.sha.outputs.value }}
