name: main-server

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:
    inputs:
      deploy_backend:
        description: "Deploy backend to DockerHub"
        required: true
        default: false
        type: boolean

jobs:
  tests_backend:
    name: Run Tests
    runs-on: ubuntu-latest
    # Tests sur PR ou push vers main (mais pas lors d'un deploy manuel)
    if: ${{ github.event_name != 'workflow_dispatch' || !inputs.deploy_backend }}
    services:
      test-db:
        image: postgres:15-alpine
        ports:
          - 3002:5432
        env:
          NODE_ENV: test
          POSTGRES_DB: giftwhisper_test
          POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install backend deps
        run: npm ci
        working-directory: ./backend

      - name: Run unit tests
        working-directory: ./backend
        run: npm run test:unit

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:integration

  deploy_backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    # Deploy SEULEMENT sur main ET en mode manuel
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && inputs.deploy_backend }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install backend deps
        run: npm ci
        working-directory: ./backend

      - name: Get short SHA
        id: sha
        run: echo "value=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push for backend
        id: backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPO }}-server:latest
            ${{ vars.DOCKERHUB_REPO }}-server:${{ steps.sha.outputs.value }}
