name: staging-server

on:
  push:
    branches: [staging]
    paths:
      - "backend/**"
jobs:
  tests_backend:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      test-db:
        image: postgres:15-alpine
        ports:
          - 3002:5432
        env:
          NODE_ENV: test
          POSTGRES_DB: giftwhisper_test
          POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # --- BACKEND ---
      - name: Install backend deps
        run: npm ci
        working-directory: ./backend

      - name: Run unit tests
        working-directory: ./backend
        run: npm run test:unit

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:integration

  build:
    runs-on: ubuntu-latest
    needs: tests_backend
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # --- BACKEND ---
      - name: Install backend deps
        run: npm ci
        working-directory: ./backend

      # - name: Run backend tests
      #   run: npm run test:unit
      #   working-directory: ./backend

      # --- GIT SHA ---
      - name: Get short SHA
        id: sha
        run: echo "value=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # --- DOCKER ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push for backend
        id: backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPO }}-staging-server:latest
            ${{ vars.DOCKERHUB_REPO }}-staging-server:${{ steps.sha.outputs.value }}
